### ISSUE TITLE
How to generate classes with composite key that includes foreign key?

### ISSUE THREAD

**Issue by SergiiShapoval** [highsource/hyperjaxb3-support#3]
Hi @highsource,
I have met another situation, which I currently can't resolve, maybe you can help:

each site in model I have mentioned before in https://github.com/highsource/hyperjaxb3-support/tree/master/m/MindBody is working separately from each other.
So when I want to persist information from different site in one database I need  to create composite key which includes current entity id and make foreign key of site as another part of composite primary key.

For example, composite primary key for Class should consist of id (Class property) and site_mobject_id (foreign key in  @ManyToOne relationship).
If I don't do this, entities will overwrite each other.

I haven't found this case in http://confluence.highsource.org/display/HJ3/Reference+-+single+page#Reference-singlepage-Supportforcompositeprimarykeys

So, how I can edit binding.xml to generate composite primary key that will include current entities' id and id of site (property in @ManyToOne relationship of @MappedSuperclass MBObject) ?

P.S. I have added the same question in stackoverflow, that others can easily find your answers - http://stackoverflow.com/questions/29465644/how-to-generate-classes-with-composite-key-that-includes-foreign-key-by-hyperjax

**Comment by highsource** [comment]
Do I get it correctly that:

* for each of the `MBObject` subclass
* you'd like to make its id to be a composite id
* consisting of entity's id (ex. Program.ID)
* as well as `MBObject`'s Site.ID

So, for `Program` the id should be a composite id consitiong of `Program.ID` and `Program.Site.ID`?

**Comment by SergiiShapoval** [comment]
Yes, it is better to take Class as example - I won't persist Program, I will persist only:
'Class'
'ClassDescription'
'Location'
'Site'
'Staff'
'MBObject'
'Visit'
'Client'
'Level'
'ArrayOfString'

So for Class we should generate composite id consisting of Class.ID and Class.Site.ID

**Comment by highsource** [comment]
Ok, here's the direction:

* http://stackoverflow.com/questions/7195990/how-to-create-a-composite-primary-key-which-contains-a-manytoone-attribute-as-a
* http://docs.oracle.com/javaee/6/api/javax/persistence/MapsId.html

**Comment by SergiiShapoval** [comment]
I have created separate `@XmlTransient` field `siteId`, getters and setters, and 3 `@IdClass`es (Int, Long, String) - it was easier way to realize and manage for me.

I have met case with `@JoinColumns`: fields for foreign keys were doubled.

Maybe someone  will like - http://stackoverflow.com/a/20147542/4594690.

IdClass was chosen to leave generated fields.

**Comment by highsource** [comment]
Ok, I've checked the code, what you want is not supported at the moment.

How it *should* work:

* Customized the `Site` with `maps-id`.
* This should tell HJ3 that your intention is to add `Site`'s id to ids (and therefore to the composite key).
* HJ3 will then generate an additional `SiteID` property in the composite id class and `@MapsId` accordingly.

Please [file an issue](https://github.com/highsource/hyperjaxb3/issues) if you want this functionality.

Implementation (more or less):

* Extend `org.jvnet.hyperjaxb3.ejb.strategy.model.base.GetIdPropertyInfos` to consider properties annotated with `maps-id` as Id properties.
* Extende `org.jvnet.hyperjaxb3.ejb.strategy.model.base.CreateIdClass` to generate `EntityId` properties.

Not so easy.

**Comment by SergiiShapoval** [comment]
yes, not easy, 
ok, thank you for help, time and quick response! :+1:
